lxc: Update lxc patch for version 2.0.8 as provided in sumo branch
Issue: ALB-3500
Signed-off-by: Ciprian Costea <ciprianmarian.costea@nxp.com>

diff --git a/dynamic-layers/virtualization-layer/recipes-containers/lxc/files/0001-Update-busybox-template-to-handle-nosuid-suid-flavor.patch b/dynamic-layers/virtualization-layer/recipes-containers/lxc/files/0001-Update-busybox-template-to-handle-nosuid-suid-flavor.patch
--- a/dynamic-layers/virtualization-layer/recipes-containers/lxc/files/0001-Update-busybox-template-to-handle-nosuid-suid-flavor.patch
+++ b/dynamic-layers/virtualization-layer/recipes-containers/lxc/files/0001-Update-busybox-template-to-handle-nosuid-suid-flavor.patch
@@ -1,7 +1,7 @@
-From d00f28250f904ac2b4af766377d08163dc2bdf5d Mon Sep 17 00:00:00 2001
-From: Vicovan Ionut-Valentin <Ionut.Vicovan@nxp.com>
-Date: Tue, 28 Aug 2018 13:59:20 +0300
-Subject: [PATCH] Update busybox template to handle nosuid/suid flavors of
+From a6cdd936c3c1ebe27b2e19b0075f649de9aced99 Mon Sep 17 00:00:00 2001
+From: =?UTF-8?q?=C2=96Vicovan=20Ionut-Valentin?= <Ionut.Vicovan@nxp.com>
+Date: Mon, 11 Feb 2019 13:03:35 +0200
+Subject: [PATCH] Update busybox template to handle nosuid/suid flavors of 
  busybox
 
 By default the template handles only the case when there is only
@@ -18,12 +18,13 @@ built into the suid binary (e.g. login, mount, passwd, su).
 
 Signed-off-by: Vicovan Ionut-Valentin <Ionut.Vicovan@nxp.com>
 Signed-off-by: Catalin Udma <catalin-dan.udma@nxp.com>
+Signed-off-by: Ciprian Costea <ciprianmarian.costea@nxp.com>
 ---
- templates/lxc-busybox.in | 62 ++++++++++++++++++++++++++++++++++++++++--------
- 1 file changed, 52 insertions(+), 10 deletions(-)
+ templates/lxc-busybox.in | 77 +++++++++++++++++++++++++++++++++---------------
+ 1 file changed, 54 insertions(+), 23 deletions(-)
 
 diff --git a/templates/lxc-busybox.in b/templates/lxc-busybox.in
-index 25e4cbf..97474fd 100644
+index 25e4cbf..7ab601f 100644
 --- a/templates/lxc-busybox.in
 +++ b/templates/lxc-busybox.in
 @@ -66,7 +66,6 @@ copy_binary()
@@ -34,7 +35,7 @@ index 25e4cbf..97474fd 100644
      res=0
      tree="\
  $rootfs/selinux \
-@@ -295,18 +294,21 @@ EOF
+@@ -295,49 +294,54 @@ EOF
  configure_busybox()
  {
      rootfs=$1
@@ -60,7 +61,20 @@ index 25e4cbf..97474fd 100644
          return 1
      fi
  
-@@ -327,17 +329,30 @@ configure_busybox()
+-    # copy host passwd
+-    if ! cp "$(which passwd)" "${rootfs}/bin"; then
+-	echo "ERROR: Failed to copy passwd binary"
+-	return 1
+-    fi
+-
+-    # copy bash binary as the container init
+-    if ! cp "$(which bash)" "${rootfs}/sbin/init"; then
+-	echo "ERROR: Failed to copy bash binary"
+-	return 1
+-    fi
+-
+-
+     # symlink busybox for the commands it supports
      # it would be nice to just use "chroot $rootfs busybox --install -s /bin"
      # but that only works right in a chroot with busybox >= 1.19.0
      pushd $rootfs/bin > /dev/null || return 1
@@ -73,9 +87,11 @@ index 25e4cbf..97474fd 100644
  
 +    has_init=`./$bb_binary --help | grep 'Currently defined functions:' -A300 | grep init`
 +    if [ -n "$has_init" ]; then
++        # relink /sbin/init
 +        ln $rootfs/bin/$bb_binary $rootfs/sbin/init
 +    fi
 +    popd > /dev/null
++ 
 +    if [ ! -f "$rootfs/etc/fstab" ]; then
      # /etc/fstab must exist for "mount -a"
      touch $rootfs/etc/fstab
@@ -94,7 +110,7 @@ index 25e4cbf..97474fd 100644
  
      return 0
  }
-@@ -443,16 +458,43 @@ if [ -z "$rootfs" ]; then
+@@ -443,16 +447,43 @@ if [ -z "$rootfs" ]; then
      fi
  fi
  
@@ -141,5 +157,5 @@ index 25e4cbf..97474fd 100644
  
  copy_configuration $path $rootfs $name
 -- 
-2.7.4
+1.9.1
 
