init-nfs-boot: Rework script
Rewrite script. Remove unused code.

Issue: ALB-2740
Signed-off-by: Iustin Dumitrescu <Iustin.Dumitrescu@nxp.com>

diff --git a/recipes-core/init-nfs-boot/files/init-nfs-boot b/recipes-core/init-nfs-boot/files/init-nfs-boot
--- a/recipes-core/init-nfs-boot/files/init-nfs-boot
+++ b/recipes-core/init-nfs-boot/files/init-nfs-boot
@@ -1,63 +1,21 @@
 #!/bin/bash
+#
 # Boot Linux from ramdisk, start networking services, insert kernel modules
 # Boot actual rootfs from NFS, as provided by command line parameters
-
-# Mount the root device if it exists
-nfsmountroot( )
-{
-    if [ -z "$nfsroot" ]; then
-        echo "Did not specify \"nfsroot=\" option."
-        return
-    fi
-
-    if [ "${readonly}" = "y" ]; then
-        roflag=-r
-    else
-        roflag=-w
-    fi
-
-    echo -n "Attempting to mount ${nfsroot} on ${rootmnt}... "
-    mount.nfs ${roflag} ${nfsrootopts} ${nfsroot} ${rootmnt} 2>/dev/null
-    mountstatus=$?
-    if [ "${mountstatus}" = "0" ]; then
-        echo "Succeeded mounting ${nfsroot}"
-    else
-        echo "Failed to mount ${nfsroot}"
-        return
-    fi
-
-    if [ -x "${rootmnt}/${init}" ]; then
-        umount /sys/kernel/debug /sys /proc
-        exec switch_root ${rootmnt} "${init}"
-    fi
-}
-
-[ -d /dev ] || mkdir -m 0755 /dev
-[ -d /root ] || mkdir -m 0700 /root
-[ -d /sys ] || mkdir /sys
-[ -d /proc ] || mkdir /proc
-[ -d /tmp ] || mkdir /tmp
+# Copyright 2018 NXP
+# SPDX-License-Identifier: BSD-3-Clause
+#
 
 mount -t proc -o nodev,noexec,nosuid proc /proc
 mount -t sysfs -o nodev,noexec,nosuid sysfs /sys
 mount -t debugfs debugfs /sys/kernel/debug
 
-ln -sf /proc/mounts /etc/mtab
-
-#Create device nodes
-[ -e /dev/console ] || mknod -m 0600 /dev/console c 5 1
-[ -e /dev/null ] || mknod /dev/null c 1 3
-
-[ -e /dev/pts ] || mkdir /dev/pts
-mount -t devpts -o noexec,nosuid,mode=0620 devpts /dev/pts
-
-#Defaults
+# Defaults
 init="/sbin/init"
 nfsroot=
 nfsrootopts=
-root=
-rootmnt="/newroot"
-readonly=y
+mountpoint="/newroot"
+readonly=
 
 ip=
 serverip=
@@ -69,45 +27,36 @@ autoconf=
 dns0=
 dns1=
 
-
-if [ -f "/etc/hostname" ] ; then
-    /bin/hostname -F /etc/hostname > /dev/null 2>&1
-fi
-
-#Parse command line options
+# Parse command line options
 for i in $(cat /proc/cmdline); do
-    case $i in
-        init=*)
-            init=${i#init=}
-            ;;
-        ip=*)
-            aux=${i#ip=}
-            IFS=':' read -r ip serverip gwip netmask hostname device autoconf dns0 dsn1 <<< "$aux"
-            unset aux
-            ;;
-        nfsroot=*)
-            nfsroot=${i#nfsroot=}
-            nfsrootopts=$(echo $nfsroot | cut -s -f 2- -d ',')
-            nfsroot=$(echo $nfsroot | cut -f 1 -d ',')
-            nfsrootopts=${nfsrootopts:+-o ${nfsrootopts}}
-            ;;
-        root=*)
-            root=${i#root=}
-            ;;
-        rootflags=*)
-            rootflags="-o ${i#rootflags=}"
-            ;;
-        rootfstype=*)
-            rootfstype="${i#rootfstype=}"
-            ;;
-        ro)
-            readonly=y
-            ;;
-        rw)
-            readonly=n
-            ;;
-    esac
+	case $i in
+		init=*)
+			init=${i#init=}
+			;;
+		ip=*)
+			aux=${i#ip=}
+			IFS=':' read -r ip serverip gwip netmask hostname device autoconf dns0 dns1 <<< "$aux"
+			unset aux
+			;;
+		nfsroot=*)
+			nfsroot=${i#nfsroot=}
+			nfsrootopts=$(echo $nfsroot | cut -s -f 2- -d ',')
+			nfsroot=$(echo $nfsroot | cut -f 1 -d ',')
+			nfsrootopts=${nfsrootopts:+-o ${nfsrootopts}}
+			;;
+		ro)
+			readonly=-r
+			;;
+		rw)
+			readonly=-w
+			;;
+	esac
 done
+
+if [ -z "$nfsroot" ]; then
+        echo "Did not specify \"nfsroot=\" option."
+	exec /bin/bash
+fi
 
 lsmod | grep -q "^sja1105pqrs\b" > /dev/null ||
     insmod /lib/modules/`uname -r`/kernel/drivers/spi/sja1105pqrs.ko
@@ -135,12 +84,32 @@ if [ "$ip" ] && [ "$device" ]; then
     fi
 fi
 
-mkdir $rootmnt
+mkdir $mountpoint
 
-# Mount final root filesystem - if any
-nfsmountroot
+echo -n "Mounting ${nfsroot} on ${mountpoint}... "
+mount.nfs ${readonly} ${nfsrootopts} ${nfsroot} ${mountpoint} 2> /dev/null
+if [ "$?" = "0" ]; then
+	echo "Mounted ${nfsroot}"
 
-# Otherwise, stick in initramfs environment as final root filesystem
-echo " "
-echo "Falling to initramfs"
+	if [ -x "${mountpoint}/${init}" ]; then
+		umount /sys/kernel/debug
+		umount /proc
+		umount /sys
+		exec switch_root ${mountpoint} "${init}"
+	fi
+fi
+
+# If we reached this point, something went wrong
+DEBUG_FILE=/nfsdebug
+
+ifconfig -a > $DEBUG_FILE
+echo >> $DEBUG_FILE
+lsmod >> $DEBUG_FILE
+echo >> $DEBUG_FILE
+mount >> $DEBUG_FILE
+echo >> $DEBUG_FILE
+
+echo -e "\nError while initializing nfs boot. Verify the debug log: $DEBUG_FILE."
+echo "Switching to minimal rootfs"
+
 exec /sbin/init
